### PR TITLE
Wolfer

### PR DESCRIPTION
**Pull request by LordWolfer**
Bugfixes and update to tutorial1, showcasing functionality.

### CODE REVIEW

**Comment by LordWolfer** [comment]
I couldn't replicate the bug mentioned in https://github.com/filipeabperes/Py3ODE/pull/1 with
```
$ python -V
Python 3.7.2
```
But I think I found - and fixed - the source of the issue.
At the very least tutorial1 is now functional on my machine without any memory issues.

**Comment by filipeabperes** [comment]
Nice, it seems to be working now. You seemed to have changed some other files (INSTALL, etc) on the previous pull request, but that ended up reverted together with the rest. Do you still wanna change those?

**Comment by filipeabperes** [comment]
Ah, I see now that this PR was actually assuming the previous PR. So Ive just kept the previous merge of the first PR.

**Comment by LordWolfer** [comment]
Nice.

I actually wanted to submit this PR with all commits, but github seemed adamant on the fact that commits in https://github.com/filipeabperes/Py3ODE/pull/1 were already merged and so creating a pull request for them makes no sense. Or I'm just bad at github. Whatever.

**Pull request merged**
